apiVersion: v1
kind: Service
metadata:
  name: registry
  labels:
    router.deis.io/routable: "true"
  annotations:
    router.deis.io/domains: registry.xiucall.com
    router.deis.io/certificates: registry.xiucall.com:registry-tls
spec:
  ports:
    - port: 80
      targetPort: 5000
  selector:
    app: registry
