apiVersion: v1
kind: ReplicationController
metadata:
  name: registry
spec:
  replicas: 1
  selector:
    name: registry
  template:
    metadata:
      labels:
        app: registry
        name: registry
    spec:
      containers:
        - name: registry
          image: registry:2
          imagePullPolicy: Always
          env:
            - name: REGISTRY_STORAGE_DELETE_ENABLED
              value: "true"
            - name: REGISTRY_LOG_LEVEL
              value: info
            - name: REGISTRY_STORAGE
              value: filesystem
          ports:
            - containerPort: 5000
          volumeMounts:
            - name: registry-storage
              mountPath: /var/lib/registry
      volumes:
        - name: registry-storage
          persistentVolumeClaim:
            claimName: registry-pv-claim
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: registry-pv-claim
  labels:
    app: registry
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 500Mi 

